In [187]:
import pandas as pd
import numpy as np
import random
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

In [188]:
# ans =  ['a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','c']
# len(ans) 

In [189]:
# ans = [1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3]
# len(ans)

In [190]:
# datavalidate = pd.DataFrame({1 :[1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              2 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              3 :[4,1,8,2,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              4 :[1,2,5,6,2,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              5 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              6 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
#                              7 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
#                              8 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              9 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                             10 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                             11 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
#                             12 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
#                             13 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
#                             14 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                             15:[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
#                             16:[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                             17:[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                             18:[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
#                             19:[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
#                             'ans' : ['a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b']})

In [191]:
datavalidate = pd.DataFrame({1 :[1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             2 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             3 :[4,1,8,2,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             4 :[1,2,5,6,2,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             5 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                            'ans' : ['a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b']})

In [192]:
datavalidate

1  2  3  4  5 ans
0   1  1  4  1  1   a
1   8  2  1  2  2   b
2   6  1  8  5  1   a
3   2  9  2  6  9   c
4   3  5  5  2  5   b
5   1  1  1  1  1   a
6   8  8  8  8  8   b
7   6  6  6  6  6   a
8   2  2  2  2  2   c
9   3  3  3  3  3   b
10  1  1  1  1  1   a
11  8  8  8  8  8   b
12  6  6  6  6  6   a
13  2  2  2  2  2   c
14  3  3  3  3  3   b
15  1  1  1  1  1   a
16  8  8  8  8  8   b
17  6  6  6  6  6   a
18  2  2  2  2  2   c
19  3  3  3  3  3   b
20  1  1  1  1  1   a
21  8  8  8  8  8   b
22  6  6  6  6  6   a
23  2  2  2  2  2   c
24  3  3  3  3  3   b
25  1  1  1  1  1   a
26  8  8  8  8  8   b
27  6  6  6  6  6   a
28  2  2  2  2  2   c
29  3  3  3  3  3   b
30  1  1  1  1  1   a
31  8  8  8  8  8   b
32  6  6  6  6  6   a
33  2  2  2  2  2   c
34  3  3  3  3  3   b
35  1  1  1  1  1   a
36  8  8  8  8  8   b
37  6  6  6  6  6   a
38  2  2  2  2  2   c
39  3  3  3  3  3   b

In [193]:
X_train, X_test, y_train, y_test = train_test_split(datavalidate.iloc[:, :-1].values, datavalidate.iloc[:,-1].values, test_size=0.4)

In [194]:
X_train

array([[1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3],
       [6, 1, 8, 5, 1],
       [6, 6, 6, 6, 6],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [1, 1, 4, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [8, 2, 1, 2, 2],
       [8, 8, 8, 8, 8],
       [2, 9, 2, 6, 9],
       [1, 1, 1, 1, 1],
       [8, 8, 8, 8, 8],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [8, 8, 8, 8, 8]], dtype=int64)

In [195]:
y_train

array(['a', 'b', 'a', 'a', 'a', 'c', 'a', 'a', 'c', 'a', 'c', 'b', 'b',
       'b', 'c', 'a', 'b', 'b', 'b', 'a', 'b', 'c', 'b', 'b'],
      dtype=object)

In [196]:
X_test

array([[2, 2, 2, 2, 2],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [3, 3, 3, 3, 3],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8],
       [3, 5, 5, 2, 5],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [8, 8, 8, 8, 8],
       [6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [1, 1, 1, 1, 1],
       [6, 6, 6, 6, 6]], dtype=int64)

In [197]:
y_test

array(['c', 'a', 'a', 'b', 'a', 'a', 'b', 'b', 'c', 'c', 'b', 'a', 'b',
       'b', 'a', 'a'], dtype=object)

In [198]:
# from sklearn.cluster import KMeans
# kmeans = KMeans(n_clusters=2)


In [199]:
# kmeans.fit(X_train)

In [200]:
s = len(X_train)//3
s

8

In [201]:
x_cluster1 = X_train[0:s]
x_cluster2 = X_train[s: 2 * s ]
x_cluster3 = X_train[2 * s:3 * s]
y_cluster1 = y_train[0:s]
y_cluster2 = y_train[s: 2 * s ]
y_cluster3 = y_train[2 * s:3 * s]

In [202]:
x_cluster1,y_cluster1

(array([[1, 1, 1, 1, 1],
        [3, 3, 3, 3, 3],
        [6, 1, 8, 5, 1],
        [6, 6, 6, 6, 6],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=int64),
 array(['a', 'b', 'a', 'a', 'a', 'c', 'a', 'a'], dtype=object))

In [203]:
x_cluster2,y_cluster3

(array([[2, 2, 2, 2, 2],
        [1, 1, 4, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [8, 2, 1, 2, 2],
        [8, 8, 8, 8, 8],
        [2, 9, 2, 6, 9],
        [1, 1, 1, 1, 1]], dtype=int64),
 array(['b', 'b', 'b', 'a', 'b', 'c', 'b', 'b'], dtype=object))

In [204]:
x_cluster3,y_cluster3

(array([[8, 8, 8, 8, 8],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [1, 1, 1, 1, 1],
        [3, 3, 3, 3, 3],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [8, 8, 8, 8, 8]], dtype=int64),
 array(['b', 'b', 'b', 'a', 'b', 'c', 'b', 'b'], dtype=object))

In [205]:
No_of_rows_cluster1,No_of_test_cases_cluster1,No_of_columms_cluster1 = x_cluster1.shape[0],X_test.shape[0],x_cluster1.shape[1]
print(No_of_rows_cluster1,"   ",No_of_test_cases_cluster1," ",No_of_columms_cluster1)

8     16   5


In [206]:
No_of_rows_cluster2,No_of_test_cases_cluster2,No_of_columms_cluster2 = x_cluster2.shape[0],X_test.shape[0],x_cluster2.shape[1]
print(No_of_rows_cluster2,"   ",No_of_test_cases_cluster2," ",No_of_columms_cluster2)

8     16   5


In [207]:
No_of_rows_cluster3,No_of_test_cases_cluster3,No_of_columms_cluster3 = x_cluster3.shape[0],X_test.shape[0],x_cluster3.shape[1]
print(No_of_rows_cluster3,"   ",No_of_test_cases_cluster3," ",No_of_columms_cluster3)

8     16   5


In [208]:
clus1 = {"x_train":x_cluster1,"y_train":y_cluster1,
         "x_test":X_test,"y_test":y_test,"No_of_test_cases":No_of_test_cases_cluster1,
         "No_of_columms":No_of_columms_cluster1,"No_of_train":No_of_rows_cluster1
        }
clus2 = {"x_train":x_cluster2,"y_train":y_cluster2,
         "x_test":X_test,"y_test":y_test,"No_of_test_cases":No_of_test_cases_cluster2,
         "No_of_columms":No_of_columms_cluster2,"No_of_train":No_of_rows_cluster2
        }
clus3 = {"x_train":x_cluster3,"y_train":y_cluster3,
         "x_test":X_test,"y_test":y_test,"No_of_test_cases":No_of_test_cases_cluster3,
         "No_of_columms":No_of_columms_cluster3,"No_of_train":No_of_rows_cluster3
        }
cluster = {0:clus1,1:clus2,2:clus3}


In [209]:
cluster

{0: {'x_train': array([[1, 1, 1, 1, 1],
         [3, 3, 3, 3, 3],
         [6, 1, 8, 5, 1],
         [6, 6, 6, 6, 6],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]], dtype=int64),
  'y_train': array(['a', 'b', 'a', 'a', 'a', 'c', 'a', 'a'], dtype=object),
  'x_test': array([[2, 2, 2, 2, 2],
         [6, 6, 6, 6, 6],
         [6, 6, 6, 6, 6],
         [3, 3, 3, 3, 3],
         [6, 6, 6, 6, 6],
         [6, 6, 6, 6, 6],
         [8, 8, 8, 8, 8],
         [3, 5, 5, 2, 5],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [8, 8, 8, 8, 8],
         [6, 6, 6, 6, 6],
         [8, 8, 8, 8, 8],
         [8, 8, 8, 8, 8],
         [1, 1, 1, 1, 1],
         [6, 6, 6, 6, 6]], dtype=int64),
  'y_test': array(['c', 'a', 'a', 'b', 'a', 'a', 'b', 'b', 'c', 'c', 'b', 'a', 'b',
         'b', 'a', 'a'], dtype=object),
  'No_of_test_cases': 16,
  'No_of_columms': 5,
  'No_of_train': 8},
 1: {'x_train': array([[2, 2, 2, 2, 2],
         [1, 

In [210]:
import math
def euclideanDistance(instance1, instance2, length):
	distance = 0
	distance = (instance1 - instance2)
	return abs(distance)

In [211]:
distances = []
import operator

In [214]:
k = 5
NeighboursSetDict1 = []
NeighboursSetDict2 = []
NeighboursSetDict3 = []
ClusterNeighbours = []

NeighboursSetDict = {0:NeighboursSetDict1,1:NeighboursSetDict2,2:NeighboursSetDict3}
for _ in range(3):
    print("cluster{}".format(_))
    for y in range(cluster[_]["No_of_test_cases"]):
        print("Test Cases will be --->",cluster[_]["x_test"][y])
        NeighboursSet = []
        for x in range(cluster[_]["No_of_columms"]-1):

#             print("x is",x)
            distances = []
            for i in range(cluster[_]["No_of_train"]):
#                 print("x train is ",cluster[_]["x_train"][i][x])
                dist = euclideanDistance(cluster[_]["x_train"][i][x],cluster[_]["x_test"][y][x],1)
                distances.append((cluster[_]["x_train"][i][x], dist))
                print("  each distance for test data {0} and train data {1} is {2}".format(cluster[_]["x_test"][y][x],cluster[_]["x_train"][i][x],distances))
            distances.sort(key=operator.itemgetter(1))
            print("          sorted",distances)
            neighbors = []
            for x in range(k):
                neighbors.append(distances[x][0])
            print("      neighbours are",neighbors)
            NeighboursSet.append(neighbors)
        print("      NeighboursSet for Each test case",NeighboursSet)
        NeighboursSetDict[_].append(NeighboursSet)
    NeighboursSetDict[_]
ClusterNeighbours.append(NeighboursSetDict)

cluster0
Test Cases will be ---> [2 2 2 2 2]
  each distance for test data 2 and train data 1 is [(1, 1)]
  each distance for test data 2 and train data 3 is [(1, 1), (3, 1)]
  each distance for test data 2 and train data 6 is [(1, 1), (3, 1), (6, 4)]
  each distance for test data 2 and train data 6 is [(1, 1), (3, 1), (6, 4), (6, 4)]
  each distance for test data 2 and train data 1 is [(1, 1), (3, 1), (6, 4), (6, 4), (1, 1)]
  each distance for test data 2 and train data 2 is [(1, 1), (3, 1), (6, 4), (6, 4), (1, 1), (2, 0)]
  each distance for test data 2 and train data 1 is [(1, 1), (3, 1), (6, 4), (6, 4), (1, 1), (2, 0), (1, 1)]
  each distance for test data 2 and train data 1 is [(1, 1), (3, 1), (6, 4), (6, 4), (1, 1), (2, 0), (1, 1), (1, 1)]
          sorted [(2, 0), (1, 1), (3, 1), (1, 1), (1, 1), (1, 1), (6, 4), (6, 4)]
      neighbours are [2, 1, 3, 1, 1]
  each distance for test data 2 and train data 1 is [(1, 1)]
  each distance for test data 2 and train data 3 is [(1, 1), (3

  each distance for test data 6 and train data 2 is [(8, 2), (3, 3), (3, 3), (1, 5), (3, 3), (2, 4)]
  each distance for test data 6 and train data 3 is [(8, 2), (3, 3), (3, 3), (1, 5), (3, 3), (2, 4), (3, 3)]
  each distance for test data 6 and train data 8 is [(8, 2), (3, 3), (3, 3), (1, 5), (3, 3), (2, 4), (3, 3), (8, 2)]
          sorted [(8, 2), (8, 2), (3, 3), (3, 3), (3, 3), (3, 3), (2, 4), (1, 5)]
      neighbours are [8, 8, 3, 3, 3]
  each distance for test data 6 and train data 8 is [(8, 2)]
  each distance for test data 6 and train data 3 is [(8, 2), (3, 3)]
  each distance for test data 6 and train data 3 is [(8, 2), (3, 3), (3, 3)]
  each distance for test data 6 and train data 1 is [(8, 2), (3, 3), (3, 3), (1, 5)]
  each distance for test data 6 and train data 3 is [(8, 2), (3, 3), (3, 3), (1, 5), (3, 3)]
  each distance for test data 6 and train data 2 is [(8, 2), (3, 3), (3, 3), (1, 5), (3, 3), (2, 4)]
  each distance for test data 6 and train data 3 is [(8, 2), (3, 3),

In [215]:
ClusterNeighbours

[{0: [[[2, 1, 3, 1, 1], [2, 1, 3, 1, 1], [2, 1, 3, 1, 1], [2, 1, 3, 1, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [6, 8, 3, 2, 1], [6, 5, 3, 2, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [6, 8, 3, 2, 1], [6, 5, 3, 2, 1]],
   [[3, 2, 1, 1, 1], [3, 2, 1, 1, 1], [3, 2, 1, 1, 1], [3, 2, 1, 5, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [6, 8, 3, 2, 1], [6, 5, 3, 2, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [6, 8, 3, 2, 1], [6, 5, 3, 2, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [8, 6, 3, 2, 1], [6, 5, 3, 2, 1]],
   [[3, 2, 1, 1, 1], [6, 3, 2, 1, 1], [6, 3, 8, 2, 1], [2, 1, 3, 1, 1]],
   [[2, 1, 3, 1, 1], [2, 1, 3, 1, 1], [2, 1, 3, 1, 1], [2, 1, 3, 1, 1]],
   [[2, 1, 3, 1, 1], [2, 1, 3, 1, 1], [2, 1, 3, 1, 1], [2, 1, 3, 1, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [8, 6, 3, 2, 1], [6, 5, 3, 2, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [6, 8, 3, 2, 1], [6, 5, 3, 2, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [8, 6, 3, 2, 1], [6, 5, 3, 2, 1]],
   [[6, 6, 3, 2, 1], [6, 3, 2, 1, 1], [8, 6, 3, 