In [244]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split

In [258]:
# datavalidate = pd.DataFrame({1 :[1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              2 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              3 :[4,1,8,2,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              4 :[1,2,5,6,2,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                              5 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
#                             'ans' : ['a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b']})

In [259]:
datavalidate = pd.DataFrame({1 :[1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             2 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             3 :[4,1,8,2,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             4 :[1,2,5,6,2,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             5 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             6 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
                             7 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
                             8 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                             9 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                            10 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                            11 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
                            12 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
                            13 :[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
                            14 :[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                            15:[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
                            16:[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                            17:[1,2,1,9,5,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3,1,8,6,2,3],
                            18:[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
                            19:[1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3,1,2,1,9,5,1,8,6,2,3],
                            'ans' : ['a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b','a','b','a','c','b']})

In [260]:
datavalidate = datavalidate.head(20)
datavalidate

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19 ans
0   1  1  4  1  1  1  1  1  1   1   1   1   1   1   1   1   1   1   1   a
1   8  2  1  2  2  2  2  2  2   2   2   2   2   2   2   2   2   2   2   b
2   6  1  8  5  1  1  1  1  1   1   1   1   1   1   1   1   1   1   1   a
3   2  9  2  6  9  9  9  9  9   9   9   9   9   9   9   9   9   9   9   c
4   3  5  5  2  5  5  5  5  5   5   5   5   5   5   5   5   5   5   5   b
5   1  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   1   1   1   a
6   8  8  8  8  8  8  8  8  8   8   8   8   8   8   8   8   8   8   8   b
7   6  6  6  6  6  6  6  6  6   6   6   6   6   6   6   6   6   6   6   a
8   2  2  2  2  2  2  2  2  2   2   2   2   2   2   2   2   2   2   2   c
9   3  3  3  3  3  3  3  3  3   3   3   3   3   3   3   3   3   3   3   b
10  1  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   1   1   1   a
11  8  8  8  8  8  2  2  8  8   8   2   2   2   8   2   8   8   2   2   b
12  6  6  6  6  6  1  1  6  6   6   1   1   1   6   1   6   6   1   1   a
13  2  2  2  2  2  9  9  2  2   2   9   9   9   2   9   2   2   9   9   c
14  3  3  3  3  3  5  5  3  3   3   5   5   5   3   5   3   3   5   5   b
15  1  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   1   1   1   a
16  8  8  8  8  8  8  8  8  8   8   8   8   8   8   8   8   8   8   8   b
17  6  6  6  6  6  6  6  6  6   6   6   6   6   6   6   6   6   6   6   a
18  2  2  2  2  2  2  2  2  2   2   2   2   2   2   2   2   2   2   2   c
19  3  3  3  3  3  3  3  3  3   3   3   3   3   3   3   3   3   3   3   b

In [261]:
datavalidate["temp"] = datavalidate["ans"].map(lambda x : x)

In [262]:
datavalidate

1  2  3  4  5  6  7  8  9  10 ...   12  13  14  15  16  17  18  19  ans  \
0   1  1  4  1  1  1  1  1  1   1 ...    1   1   1   1   1   1   1   1    a   
1   8  2  1  2  2  2  2  2  2   2 ...    2   2   2   2   2   2   2   2    b   
2   6  1  8  5  1  1  1  1  1   1 ...    1   1   1   1   1   1   1   1    a   
3   2  9  2  6  9  9  9  9  9   9 ...    9   9   9   9   9   9   9   9    c   
4   3  5  5  2  5  5  5  5  5   5 ...    5   5   5   5   5   5   5   5    b   
5   1  1  1  1  1  1  1  1  1   1 ...    1   1   1   1   1   1   1   1    a   
6   8  8  8  8  8  8  8  8  8   8 ...    8   8   8   8   8   8   8   8    b   
7   6  6  6  6  6  6  6  6  6   6 ...    6   6   6   6   6   6   6   6    a   
8   2  2  2  2  2  2  2  2  2   2 ...    2   2   2   2   2   2   2   2    c   
9   3  3  3  3  3  3  3  3  3   3 ...    3   3   3   3   3   3   3   3    b   
10  1  1  1  1  1  1  1  1  1   1 ...    1   1   1   1   1   1   1   1    a   
11  8  8  8  8  8  2  2  8  8   8 ...    2   2   8   2   8   8   2   2    b   
12  6  6  6  6  6  1  1  6  6   6 ...    1   1   6   1   6   6   1   1    a   
13  2  2  2  2  2  9  9  2  2   2 ...    9   9   2   9   2   2   9   9    c   
14  3  3  3  3  3  5  5  3  3   3 ...    5   5   3   5   3   3   5   5    b   
15  1  1  1  1  1  1  1  1  1   1 ...    1   1   1   1   1   1   1   1    a   
16  8  8  8  8  8  8  8  8  8   8 ...    8   8   8   8   8   8   8   8    b   
17  6  6  6  6  6  6  6  6  6   6 ...    6   6   6   6   6   6   6   6    a   
18  2  2  2  2  2  2  2  2  2   2 ...    2   2   2   2   2   2   2   2    c   
19  3  3  3  3  3  3  3  3  3   3 ...    3   3   3   3   3   3   3   3    b   

   temp  
0     a  
1     b  
2     a  
3     c  
4     b  
5     a  
6     b  
7     a  
8     c  
9     b  
10    a  
11    b  
12    a  
13    c  
14    b  
15    a  
16    b  
17    a  
18    c  
19    b  

[20 rows x 21 columns]

In [281]:
X_train, X_test, y_train, y_test = train_test_split(datavalidate.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20]].values, datavalidate.iloc[:,19].values, test_size=0.4)

In [282]:
X_train

array([[6, 6, 6, 6, 6, 1, 1, 6, 6, 6, 1, 1, 1, 6, 1, 6, 6, 1, 1, 'a'],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 'b'],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'c'],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 'a'],
       [8, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'b'],
       [3, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 'b'],
       [1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 'b'],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 'b'],
       [2, 9, 2, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 'c'],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'c']],
      dtype=object)

In [283]:
X_train

array([[6, 6, 6, 6, 6, 1, 1, 6, 6, 6, 1, 1, 1, 6, 1, 6, 6, 1, 1, 'a'],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 'b'],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'c'],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 'a'],
       [8, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'b'],
       [3, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 'b'],
       [1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 'b'],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 'b'],
       [2, 9, 2, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 'c'],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 'c']],
      dtype=object)

In [284]:
y_train

array(['a', 'b', 'c', 'a', 'a', 'b', 'b', 'a', 'b', 'b', 'c', 'c'],
      dtype=object)

In [285]:
X_test

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
       [3, 3, 3, 3, 3, 5, 5, 3, 3, 3, 5, 5, 5, 3, 5, 3, 3, 5, 5, 'b'],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 'a'],
       [2, 2, 2, 2, 2, 9, 9, 2, 2, 2, 9, 9, 9, 2, 9, 2, 2, 9, 9, 'c'],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 'b'],
       [6, 1, 8, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
       [8, 8, 8, 8, 8, 2, 2, 8, 8, 8, 2, 2, 2, 8, 2, 8, 8, 2, 2, 'b']],
      dtype=object)

In [318]:
x_cluster1 = []
x_cluster2 = []
x_cluster3 = []
y_cluster1 = []
y_cluster2 = []
y_cluster3 = []
for _ in X_train:
    if _[-1] == 'a':
        x_cluster1.append(_[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]])
#         y_cluster1.append(_[[-1]])
    elif _[-1] == 'b':
        x_cluster2.append(_[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]])
#         y_cluster2.append(_)
    else:
        x_cluster3.append(_[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]) 
#         y_cluster3.append(_)
for _ in y_train:
#     print(_)
    if _ == 'a':
        y_cluster1.append(_)
#         y_cluster1.append(_[[-1]])
    elif _ == 'b':
        y_cluster2.append(_)
#         y_cluster2.append(_)
    else:
        y_cluster3.append(_) 
#         y_cluster3.append(_)
        

In [287]:
type(x_cluster1)


list

In [319]:
x_cluster1


[array([6, 6, 6, 6, 6, 1, 1, 6, 6, 6, 1, 1, 1, 6, 1, 6, 6, 1, 1],
       dtype=object),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=object),
 array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       dtype=object),
 array([1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=object)]

In [320]:
y_cluster1

['a', 'a', 'a', 'a']

In [321]:
x_cluster2

[array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       dtype=object),
 array([8, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       dtype=object),
 array([3, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       dtype=object),
 array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       dtype=object),
 array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       dtype=object)]

In [322]:
y_cluster2

['b', 'b', 'b', 'b', 'b']

In [323]:
x_cluster3

[array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       dtype=object),
 array([2, 9, 2, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       dtype=object),
 array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       dtype=object)]

In [324]:
y_cluster3

['c', 'c', 'c']

In [325]:
No_of_columms_cluster1 = len(x_cluster3[0])
No_of_columms_cluster1

No_of_rows_cluster1,No_of_test_cases_cluster1,No_of_columms_cluster1 = len(x_cluster1),len(X_test),len(x_cluster1[0])
print(No_of_rows_cluster1,"   ",No_of_test_cases_cluster1," ",No_of_columms_cluster1)

No_of_rows_cluster2,No_of_test_cases_cluster2,No_of_columms_cluster2 = len(x_cluster2),len(X_test),len(x_cluster2[0])
print(No_of_rows_cluster2,"   ",No_of_test_cases_cluster2," ",No_of_columms_cluster2)

No_of_rows_cluster3,No_of_test_cases_cluster3,No_of_columms_cluster3 = len(x_cluster3),len(X_test),len(x_cluster3[0])
print(No_of_rows_cluster3,"   ",No_of_test_cases_cluster3," ",No_of_columms_cluster3)

19

In [329]:
clus1 = {"x_train":x_cluster1,"y_train":y_cluster1,
         "x_test":X_test,"y_test":y_test,"No_of_test_cases":No_of_test_cases_cluster1,
         "No_of_columms":No_of_columms_cluster1,"No_of_train":No_of_rows_cluster1
        }
clus2 = {"x_train":x_cluster2,"y_train":y_cluster2,
         "x_test":X_test,"y_test":y_test,"No_of_test_cases":No_of_test_cases_cluster2,
         "No_of_columms":No_of_columms_cluster2,"No_of_train":No_of_rows_cluster2
        }
clus3 = {"x_train":x_cluster3,"y_train":y_cluster3,
         "x_test":X_test,"y_test":y_test,"No_of_test_cases":No_of_test_cases_cluster3,
         "No_of_columms":No_of_columms_cluster3,"No_of_train":No_of_rows_cluster3
        }
cluster = {0:clus1,1:clus2,2:clus3}

In [330]:
cluster[0]

{'x_train': [array([6, 6, 6, 6, 6, 1, 1, 6, 6, 6, 1, 1, 1, 6, 1, 6, 6, 1, 1],
        dtype=object),
  array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        dtype=object),
  array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        dtype=object),
  array([1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        dtype=object)],
 'y_train': ['a', 'a', 'a', 'a'],
 'x_test': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
        [3, 3, 3, 3, 3, 5, 5, 3, 3, 3, 5, 5, 5, 3, 5, 3, 3, 5, 5, 'b'],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 'a'],
        [2, 2, 2, 2, 2, 9, 9, 2, 2, 2, 9, 9, 9, 2, 9, 2, 2, 9, 9, 'c'],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 'b'],
        [6, 1, 8, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
        [8, 8, 8, 8, 8, 2, 2, 8, 8, 8, 2, 2, 2, 8, 2, 8, 8, 2, 2, 'b']],
       

In [331]:
cluster[1]

{'x_train': [array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
        dtype=object),
  array([8, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        dtype=object),
  array([3, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        dtype=object),
  array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        dtype=object),
  array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
        dtype=object)],
 'y_train': ['b', 'b', 'b', 'b', 'b'],
 'x_test': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'a'],
        [3, 3, 3, 3, 3, 5, 5, 3, 3, 3, 5, 5, 5, 3, 5, 3, 3, 5, 5, 'b'],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 'a'],
        [2, 2, 2, 2, 2, 9, 9, 2, 2, 2, 9, 9, 9, 2, 9, 2, 2, 9, 9, 'c'],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 'b'],
        [6, 1, 8, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [332]:
import math
def euclideanDistance(instance1, instance2, length):
	distance = 0
	distance = (int(instance1) - int(instance2))
	return abs(distance)

In [333]:
distances = []
import operator

In [334]:
# k = 3
# NeighboursSetDict1 = []
# NeighboursSetDict2 = []
# NeighboursSetDict3 = []
# ClusterNeighbours = {}

# NeighboursSetDict = {0:NeighboursSetDict1,1:NeighboursSetDict2,2:NeighboursSetDict3}
# for _ in range(3):
#     print("cluster{}".format(_))
#     for y in range(cluster[_]["No_of_test_cases"]):
#         print("Test Cases will be --->",cluster[_]["x_test"][y])
#         NeighboursSet = []
#         for x in range(cluster[_]["No_of_columms"]-1):

# #             print("x is",x)
#             distances = []
#             for i in range(cluster[_]["No_of_train"]):
# #                 print("x train is ",cluster[_]["x_train"][i][x])
#                 dist = euclideanDistance(cluster[_]["x_train"][i][x],cluster[_]["x_test"][y][x],1)
#                 distances.append((cluster[_]["x_train"][i][x], dist))
#                 print("  each distance for test data {0} and train data {1} is {2}".format(cluster[_]["x_test"][y][x],cluster[_]["x_train"][i][x],distances))
#             distances.sort(key=operator.itemgetter(1))
#             print("          sorted",distances)
#             neighbors = []
#             for x in range(k):
                
#                 neighbors.append(distances[x][1])
# #                 print(x,neighbors)
#             print("      neighbours are",neighbors)
#             NeighboursSet.append(neighbors)
#         print("      NeighboursSet for Each test case",NeighboursSet)
# #         NeighboursSetDict[_].append(NeighboursSet)
#     ClusterNeighbours[_] = NeighboursSetDict[_]
# # ClusterNeighbours.append(NeighboursSetDict)

In [335]:
ClusterNeighbours

{0: {0: {'total': 58, 'F1Sum': 5, 'F2Sum': 5, 'F3Sum': 8, 'F4Sum': 5},
  1: {'total': 126, 'F1Sum': 11, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 4},
  2: {'total': 163, 'F1Sum': 3, 'F2Sum': 10, 'F3Sum': 3, 'F4Sum': 7}},
 1: {0: {'total': 58, 'F1Sum': 5, 'F2Sum': 5, 'F3Sum': 8, 'F4Sum': 5},
  1: {'total': 126, 'F1Sum': 11, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 4},
  2: {'total': 163, 'F1Sum': 3, 'F2Sum': 10, 'F3Sum': 3, 'F4Sum': 7}},
 2: {0: {'total': 139, 'F1Sum': 7, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 7},
  1: {'total': 70, 'F1Sum': 5, 'F2Sum': 3, 'F3Sum': 4, 'F4Sum': 2},
  2: {'total': 145, 'F1Sum': 3, 'F2Sum': 8, 'F3Sum': 3, 'F4Sum': 5}},
 3: {0: {'total': 122, 'F1Sum': 5, 'F2Sum': 5, 'F3Sum': 2, 'F4Sum': 5},
  1: {'total': 93, 'F1Sum': 6, 'F2Sum': 5, 'F3Sum': 5, 'F4Sum': 7},
  2: {'total': 197, 'F1Sum': 12, 'F2Sum': 11, 'F3Sum': 12, 'F4Sum': 8}},
 4: {0: {'total': 200, 'F1Sum': 6, 'F2Sum': 6, 'F3Sum': 7, 'F4Sum': 6},
  1: {'total': 88, 'F1Sum': 8, 'F2Sum': 4, 'F3Sum': 5, 'F4Sum': 1},
  2: {'total'

In [336]:
ClusterNeighbours[0]

{0: {'total': 58, 'F1Sum': 5, 'F2Sum': 5, 'F3Sum': 8, 'F4Sum': 5},
 1: {'total': 126, 'F1Sum': 11, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 4},
 2: {'total': 163, 'F1Sum': 3, 'F2Sum': 10, 'F3Sum': 3, 'F4Sum': 7}}

In [337]:
# def featuretotal(ClusterNeighbours,IndicesToFeature):
#     FeatureTotalSum = 0
# #     print(ClusterNeighbours)
#     for each_row in ClusterNeighbours:
# #         print(each_row)
  
#         x,y = each_row[IndicesToFeature]
#         FeatureTotalSum += x+y
# #     print(ClusterNeighbours1Total)
#     return FeatureTotalSum

In [338]:
# def cluster_total(ClusterNeighboursList):
#     ClusterTotal = 0
#     for each_row in ClusterNeighboursList:
#         for x,y in each_row:
#             ClusterTotal += x+y
# #     print(ClusterNeighbours1Total)
#     return ClusterTotal

In [339]:
def cluster_total(ClusterNeighboursList):
    ClusterTotal = 0
    for each_row in ClusterNeighboursList:
        x,y = each_row
        ClusterTotal += x+y
#     print(ClusterNeighbours1Total)
    return ClusterTotal

In [340]:
# ClusterNeighbours[0][1]

ClusterNeighbours1Total = cluster_total(ClusterNeighbours[0])
ClusterNeighbours1Total

ClusterNeighbours2Total = cluster_total(ClusterNeighbours[1])
ClusterNeighbours2Total

ClusterNeighbours3Total = cluster_total(ClusterNeighbours[2])
ClusterNeighbours3Total

In [341]:
# ClusterNeighbours1Total = 0
# for each_row in ClusterNeighbours[0]:
#     for x,y in each_row:
#         ClusterNeighbours1Total += x+y
# #     print(ClusterNeighbours1Total)
# ClusterNeighbours1Total

In [342]:
# Cluster1_feature1 = featuretotal(ClusterNeighbours[0],0)
# Cluster1_feature1

# Cluster1_feature2 = featuretotal(ClusterNeighbours[0],1)
# Cluster1_feature2

# Cluster1_feature3 = featuretotal(ClusterNeighbours[0],2)
# Cluster1_feature3

# Cluster1_feature4 = featuretotal(ClusterNeighbours[0],3)
# Cluster1_feature4



In [343]:
# Cluster2_feature1 = featuretotal(ClusterNeighbours[1],0)
# Cluster2_feature1

# Cluster2_feature2 = featuretotal(ClusterNeighbours[1],1)
# Cluster2_feature2

# Cluster2_feature3 = featuretotal(ClusterNeighbours[1],2)
# Cluster2_feature3

# Cluster2_feature4 = featuretotal(ClusterNeighbours[1],3)
# Cluster2_feature4

In [344]:
# Cluster3_feature1 = featuretotal(ClusterNeighbours[2],0)
# Cluster3_feature1
# Cluster3_feature2 = featuretotal(ClusterNeighbours[2],1)
# Cluster3_feature2
# Cluster3_feature3 = featuretotal(ClusterNeighbours[2],2)
# Cluster3_feature3
# Cluster3_feature4 = featuretotal(ClusterNeighbours[2],3)
# Cluster3_feature4

In [345]:
# Cluster1_feature2 = 0
# for each_row in ClusterNeighbours[0]:
#     x,y = each_row[1]
#     Cluster1_feature2 += x+y
# Cluster1_feature2

In [346]:
# Cluster1_feature3 = 0
# for each_row in ClusterNeighbours[0]:
#     x,y = each_row[2]
#     Cluster1_feature3 += x+y
# Cluster1_feature3

In [347]:
# Cluster1_feature4 = 0
# for each_row in ClusterNeighbours[0]:
# #     print(each_row)
# #     print(each_row[0])
#     x,y = each_row[3]
# #     print(x,y)
#     Cluster1_feature4 += x+y
# Cluster1_feature4

In [348]:
ClusterNeighbours[1]

{0: {'total': 58, 'F1Sum': 5, 'F2Sum': 5, 'F3Sum': 8, 'F4Sum': 5},
 1: {'total': 126, 'F1Sum': 11, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 4},
 2: {'total': 163, 'F1Sum': 3, 'F2Sum': 10, 'F3Sum': 3, 'F4Sum': 7}}

In [349]:
ClusterNeighbours2Total = cluster_total(ClusterNeighbours[1])
ClusterNeighbours2Total
# for each_row in ClusterNeighbours[1]:
#     for x,y in each_row:
#         ClusterNeighbours2Total += x+y
# #     print(ClusterNeighbours1Total)
# ClusterNeighbours2Total

TypeError: 'int' object is not iterable

In [350]:
ClusterNeighbours[2]

{0: {'total': 139, 'F1Sum': 7, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 7},
 1: {'total': 70, 'F1Sum': 5, 'F2Sum': 3, 'F3Sum': 4, 'F4Sum': 2},
 2: {'total': 145, 'F1Sum': 3, 'F2Sum': 8, 'F3Sum': 3, 'F4Sum': 5}}

In [351]:
# ClusterNeighbours3Total = cluster_total(ClusterNeighbours[2])
# ClusterNeighbours3Total
# # for each_row in ClusterNeighbours[2]:
# #     for x,y in each_row:
# #         ClusterNeighbours3Total += x+y
# # #     print(ClusterNeighbours1Total)
# # ClusterNeighbours3Total

In [352]:
# ClusterNewForm = {
#     0:{
#         "TotalSum":ClusterNeighbours1Total,"F1Sum":Cluster1_feature1,"F2Sum":Cluster1_feature2,"F3Sum":Cluster1_feature3,"F4Sum":Cluster1_feature4
#     },
#     1:{
#         "TotalSum":ClusterNeighbours2Total,"F1Sum":Cluster2_feature1,"F2Sum":Cluster2_feature2,"F3Sum":Cluster2_feature3,"F4Sum":Cluster2_feature4
#     },
#     2:{
#         "TotalSum":ClusterNeighbours3Total,"F1Sum":Cluster3_feature1,"F2Sum":Cluster3_feature2,"F3Sum":Cluster3_feature3,"F4Sum":Cluster3_feature4
#     }
# }

In [353]:
# ClusterNewForm

In [354]:
No_of_test_cases = X_test.shape[0]
No_of_test_cases

8

In [355]:
def cluster_total(ClusterNeighboursList):
    ClusterTotal = 0
    for each_row in ClusterNeighboursList:
        x,y,z = each_row
        ClusterTotal += x+y+z
#     print(ClusterNeighbours1Total)
    return ClusterTotal

In [356]:
def featuretotal(ClusterNeighbours,IndicesToFeature):
    FeatureTotalSum = 0
#     print(ClusterNeighbours)
    x,y,z = ClusterNeighbours[IndicesToFeature]
    FeatureTotalSum += x+y+z
#     print(ClusterNeighbours1Total)
    return FeatureTotalSum

In [360]:
k = 3
NeighboursSetDict1 = []
NeighboursSetDict2 = []
NeighboursSetDict3 = []
ClusterNeighbours = {}

NeighboursSetDict = {0:NeighboursSetDict1,1:NeighboursSetDict2,2:NeighboursSetDict3}
for _ in range(No_of_test_cases):
    
    ClusterDict = {}
    print("Test Cases will be --->",X_test[_])
    for y in range(3):
        dictnew = {}
        print("cluster{}".format(_))
        NeighboursSet = []
        for x in range(cluster[y]["No_of_columms"]-1):

#             print("x is",x)
            distances = []
            for i in range(cluster[y]["No_of_train"]):
                dist = euclideanDistance(cluster[y]["x_train"][i][x],cluster[y]["x_test"][_][x],1)
                distances.append((cluster[y]["x_train"][i][x], dist))
                print("  each distance for test data {0} and train data {1} is {2}".format(cluster[y]["x_test"][_][x],cluster[y]["x_train"][i][x],distances))
            distances.sort(key=operator.itemgetter(1))
            print("          sorted",distances)
            neighbors = []
            for m in range(k):
                
                neighbors.append(distances[m][1])
            print("      neighbours are",neighbors)
            NeighboursSet.append(neighbors)
        print("      NeighboursSet for Each test case",NeighboursSet)
        dictnew["total"] = cluster_total(NeighboursSet)
        dictnew["F1Sum"] = featuretotal(NeighboursSet,0)
        dictnew["F2Sum"] = featuretotal(NeighboursSet,1)
        dictnew["F3Sum"] = featuretotal(NeighboursSet,2)
        dictnew["F4Sum"] = featuretotal(NeighboursSet,3)
        dictnew["F5Sum"] = featuretotal(NeighboursSet,4)
        dictnew["F6Sum"] = featuretotal(NeighboursSet,5)
        dictnew["F7Sum"] = featuretotal(NeighboursSet,6)
        dictnew["F8Sum"] = featuretotal(NeighboursSet,7)
        dictnew["F9Sum"] = featuretotal(NeighboursSet,8)
        dictnew["F10Sum"] = featuretotal(NeighboursSet,9)
        dictnew["F11Sum"] = featuretotal(NeighboursSet,10)
        dictnew["F12Sum"] = featuretotal(NeighboursSet,11)
        dictnew["F13Sum"] = featuretotal(NeighboursSet,12)
        dictnew["F14Sum"] = featuretotal(NeighboursSet,13)
        dictnew["F15Sum"] = featuretotal(NeighboursSet,14)
        
        ClusterDict[y] = dictnew
        print(dictnew)
    ClusterNeighbours[_] = ClusterDict

# ClusterNeighbours.append(NeighboursSetDict)

Test Cases will be ---> [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 'a']
cluster0
  each distance for test data 1 and train data 6 is [(6, 5)]
  each distance for test data 1 and train data 1 is [(6, 5), (1, 0)]
  each distance for test data 1 and train data 6 is [(6, 5), (1, 0), (6, 5)]
  each distance for test data 1 and train data 1 is [(6, 5), (1, 0), (6, 5), (1, 0)]
          sorted [(1, 0), (1, 0), (6, 5), (6, 5)]
      neighbours are [0, 0, 5]
  each distance for test data 1 and train data 6 is [(6, 5)]
  each distance for test data 1 and train data 1 is [(6, 5), (1, 0)]
  each distance for test data 1 and train data 6 is [(6, 5), (1, 0), (6, 5)]
  each distance for test data 1 and train data 1 is [(6, 5), (1, 0), (6, 5), (1, 0)]
          sorted [(1, 0), (1, 0), (6, 5), (6, 5)]
      neighbours are [0, 0, 5]
  each distance for test data 1 and train data 6 is [(6, 5)]
  each distance for test data 1 and train data 1 is [(6, 5), (1, 0)]
  each distance for test data 1 and train data 

  each distance for test data 6 and train data 8 is [(8, 2)]
  each distance for test data 6 and train data 2 is [(8, 2), (2, 4)]
  each distance for test data 6 and train data 5 is [(8, 2), (2, 4), (5, 1)]
  each distance for test data 6 and train data 3 is [(8, 2), (2, 4), (5, 1), (3, 3)]
  each distance for test data 6 and train data 8 is [(8, 2), (2, 4), (5, 1), (3, 3), (8, 2)]
          sorted [(5, 1), (8, 2), (8, 2), (3, 3), (2, 4)]
      neighbours are [1, 2, 2]
  each distance for test data 6 and train data 8 is [(8, 2)]
  each distance for test data 6 and train data 2 is [(8, 2), (2, 4)]
  each distance for test data 6 and train data 5 is [(8, 2), (2, 4), (5, 1)]
  each distance for test data 6 and train data 3 is [(8, 2), (2, 4), (5, 1), (3, 3)]
  each distance for test data 6 and train data 8 is [(8, 2), (2, 4), (5, 1), (3, 3), (8, 2)]
          sorted [(5, 1), (8, 2), (8, 2), (3, 3), (2, 4)]
      neighbours are [1, 2, 2]
  each distance for test data 6 and train data 8 is 

      neighbours are [0, 1, 2]
      NeighboursSet for Each test case [[0, 0, 5], [0, 1, 2], [0, 2, 2], [0, 1, 1], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]
{'total': 56, 'F1Sum': 5, 'F2Sum': 3, 'F3Sum': 4, 'F4Sum': 2, 'F5Sum': 3, 'F6Sum': 3, 'F7Sum': 3, 'F8Sum': 3, 'F9Sum': 3, 'F10Sum': 3, 'F11Sum': 3, 'F12Sum': 3, 'F13Sum': 3, 'F14Sum': 3, 'F15Sum': 3}
cluster5
  each distance for test data 3 and train data 2 is [(2, 1)]
  each distance for test data 3 and train data 2 is [(2, 1), (2, 1)]
  each distance for test data 3 and train data 2 is [(2, 1), (2, 1), (2, 1)]
          sorted [(2, 1), (2, 1), (2, 1)]
      neighbours are [1, 1, 1]
  each distance for test data 3 and train data 2 is [(2, 1)]
  each distance for test data 3 and train data 9 is [(2, 1), (9, 6)]
  each distance for test data 3 and train data 2 is [(2, 1), (9, 6), (2, 1)]
          sorted [(2, 1), (2, 1), (

In [361]:
ClusterNeighbours

{0: {0: {'total': 58,
   'F1Sum': 5,
   'F2Sum': 5,
   'F3Sum': 8,
   'F4Sum': 5,
   'F5Sum': 5,
   'F6Sum': 0,
   'F7Sum': 0,
   'F8Sum': 5,
   'F9Sum': 5,
   'F10Sum': 5,
   'F11Sum': 0,
   'F12Sum': 0,
   'F13Sum': 0,
   'F14Sum': 5,
   'F15Sum': 0},
  1: {'total': 126,
   'F1Sum': 11,
   'F2Sum': 7,
   'F3Sum': 6,
   'F4Sum': 4,
   'F5Sum': 7,
   'F6Sum': 7,
   'F7Sum': 7,
   'F8Sum': 7,
   'F9Sum': 7,
   'F10Sum': 7,
   'F11Sum': 7,
   'F12Sum': 7,
   'F13Sum': 7,
   'F14Sum': 7,
   'F15Sum': 7},
  2: {'total': 163,
   'F1Sum': 3,
   'F2Sum': 10,
   'F3Sum': 3,
   'F4Sum': 7,
   'F5Sum': 10,
   'F6Sum': 10,
   'F7Sum': 10,
   'F8Sum': 10,
   'F9Sum': 10,
   'F10Sum': 10,
   'F11Sum': 10,
   'F12Sum': 10,
   'F13Sum': 10,
   'F14Sum': 10,
   'F15Sum': 10}},
 1: {0: {'total': 58,
   'F1Sum': 5,
   'F2Sum': 5,
   'F3Sum': 8,
   'F4Sum': 5,
   'F5Sum': 5,
   'F6Sum': 0,
   'F7Sum': 0,
   'F8Sum': 5,
   'F9Sum': 5,
   'F10Sum': 5,
   'F11Sum': 0,
   'F12Sum': 0,
   'F13Sum': 0,
   'F14

In [312]:
ClusterNeighbours

{0: {0: {'total': 58, 'F1Sum': 5, 'F2Sum': 5, 'F3Sum': 8, 'F4Sum': 5},
  1: {'total': 126, 'F1Sum': 11, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 4},
  2: {'total': 163, 'F1Sum': 3, 'F2Sum': 10, 'F3Sum': 3, 'F4Sum': 7}},
 1: {0: {'total': 58, 'F1Sum': 5, 'F2Sum': 5, 'F3Sum': 8, 'F4Sum': 5},
  1: {'total': 126, 'F1Sum': 11, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 4},
  2: {'total': 163, 'F1Sum': 3, 'F2Sum': 10, 'F3Sum': 3, 'F4Sum': 7}},
 2: {0: {'total': 139, 'F1Sum': 7, 'F2Sum': 7, 'F3Sum': 6, 'F4Sum': 7},
  1: {'total': 70, 'F1Sum': 5, 'F2Sum': 3, 'F3Sum': 4, 'F4Sum': 2},
  2: {'total': 145, 'F1Sum': 3, 'F2Sum': 8, 'F3Sum': 3, 'F4Sum': 5}},
 3: {0: {'total': 122, 'F1Sum': 5, 'F2Sum': 5, 'F3Sum': 2, 'F4Sum': 5},
  1: {'total': 93, 'F1Sum': 6, 'F2Sum': 5, 'F3Sum': 5, 'F4Sum': 7},
  2: {'total': 197, 'F1Sum': 12, 'F2Sum': 11, 'F3Sum': 12, 'F4Sum': 8}},
 4: {0: {'total': 200, 'F1Sum': 6, 'F2Sum': 6, 'F3Sum': 7, 'F4Sum': 6},
  1: {'total': 88, 'F1Sum': 8, 'F2Sum': 4, 'F3Sum': 5, 'F4Sum': 1},
  2: {'total'

In [363]:
import operator
Prior_columns = {}
for t in range(No_of_test_cases):
    dict_col = {}
    for c in range(3):
        SortList = []
        print(ClusterNeighbours[t][c]["F1Sum"]," ",ClusterNeighbours[t][c]["total"])
        print(ClusterNeighbours[t][c]["F2Sum"]," ",ClusterNeighbours[t][c]["total"])
        print(ClusterNeighbours[t][c]["F3Sum"]," ",ClusterNeighbours[t][c]["total"])
        print(ClusterNeighbours[t][c]["F4Sum"]," ",ClusterNeighbours[t][c]["total"])
        
        feature1 = int(ClusterNeighbours[t][c]["F1Sum"]/ClusterNeighbours[t][c]["total"])
        feature2 = int(ClusterNeighbours[t][c]["F2Sum"]/ClusterNeighbours[t][c]["total"])
        feature3 = int(ClusterNeighbours[t][c]["F3Sum"]/ClusterNeighbours[t][c]["total"])
        feature4 = int(ClusterNeighbours[t][c]["F4Sum"]/ClusterNeighbours[t][c]["total"])
        feature5 = int(ClusterNeighbours[t][c]["F5Sum"]/ClusterNeighbours[t][c]["total"])
        feature6 = int(ClusterNeighbours[t][c]["F6Sum"]/ClusterNeighbours[t][c]["total"])
        feature7 = int(ClusterNeighbours[t][c]["F7Sum"]/ClusterNeighbours[t][c]["total"])
        feature8 = int(ClusterNeighbours[t][c]["F8Sum"]/ClusterNeighbours[t][c]["total"])
        feature9 = int(ClusterNeighbours[t][c]["F9Sum"]/ClusterNeighbours[t][c]["total"])
        feature10 = int(ClusterNeighbours[t][c]["F10Sum"]/ClusterNeighbours[t][c]["total"])
        feature11 = int(ClusterNeighbours[t][c]["F11Sum"]/ClusterNeighbours[t][c]["total"])
        feature12 = int(ClusterNeighbours[t][c]["F12Sum"]/ClusterNeighbours[t][c]["total"])
        feature13 = int(ClusterNeighbours[t][c]["F13Sum"]/ClusterNeighbours[t][c]["total"])
        feature14 = int(ClusterNeighbours[t][c]["F14Sum"]/ClusterNeighbours[t][c]["total"])
        feature15 = int(ClusterNeighbours[t][c]["F15Sum"]/ClusterNeighbours[t][c]["total"])
        
#         feature1 = ClusterNeighbours[t][c]["F1Sum"]/ClusterNeighbours[t][c]["total"]
#         feature2 = ClusterNeighbours[t][c]["F2Sum"]/ClusterNeighbours[t][c]["total"]
#         feature3 = ClusterNeighbours[t][c]["F3Sum"]/ClusterNeighbours[t][c]["total"]
#         feature4 = ClusterNeighbours[t][c]["F4Sum"]/ClusterNeighbours[t][c]["total"]
        print(str(feature1) , " " , str(feature2) ,  " " ,  str(feature3) , " " , str(feature4))
        SortList.append([[feature1,1],[feature2,2],[feature3,3],[feature4,4],[feature5,5],[feature6,6],
                         [feature7,7],[feature8,8],[feature9,9],[feature10,10],[feature11,11],[feature12,12],
                        [feature13,13],[feature14,14],[feature15,15]])
        print(SortList[0])
        SortList[0].sort(key=operator.itemgetter(0))
        
        #we are taking the less valued columns here
        SortList = SortList[0][0:5]
        print(SortList)
        dict_col[c] =  SortList
    Prior_columns[t] = dict_col


5   58
5   58
8   58
5   58
0   0   0   0
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [0, 10], [0, 11], [0, 12], [0, 13], [0, 14], [0, 15]]
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
11   126
7   126
6   126
4   126
0   0   0   0
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [0, 10], [0, 11], [0, 12], [0, 13], [0, 14], [0, 15]]
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
3   163
10   163
3   163
7   163
0   0   0   0
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [0, 10], [0, 11], [0, 12], [0, 13], [0, 14], [0, 15]]
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
5   58
5   58
8   58
5   58
0   0   0   0
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [0, 10], [0, 11], [0, 12], [0, 13], [0, 14], [0, 15]]
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]
11   126
7   126
6   126
4   126
0   0   0   0
[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [0, 10], [0, 11], [0, 12], [0,

In [364]:
SortList

[[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]

In [365]:
Prior_columns

{0: {0: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  1: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  2: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]},
 1: {0: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  1: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  2: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]},
 2: {0: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  1: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  2: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]},
 3: {0: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  1: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  2: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]},
 4: {0: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  1: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  2: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]},
 5: {0: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  1: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  2: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]]},
 6: {0: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  1: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
  2: [[0, 1], [0, 2], [0, 3], [0,

In [366]:
def predict(test_index):
    value = Prior_columns[test_index]
    print(X_test[test_index])
    Cluster1Nor = Prior_columns[test_index][0]
    NormalizeFor1 = 0
    for __ in Cluster1Nor:
        print('__ is ',__)
        x,y = __
        NormalizeFor1 += x
    print("NormalizeFor1 for ",NormalizeFor1)
    Cluster2Nor = Prior_columns[test_index][1]
    NormalizeFor2 = 0
    
    for __ in Cluster2Nor:
        print('__ is ',__)
        x,y = __
        NormalizeFor2 += x
    print("NormalizeFor2 for ",NormalizeFor2)
    Cluster3Nor = Prior_columns[test_index][2]
    
    NormalizeFor3 = 0
    for __ in Cluster3Nor:
        print('__ is ',__)
        x,y = __
        NormalizeFor3 += x
    print("NormalizeFor3 for ",NormalizeFor3)
    maximum = max(NormalizeFor1,NormalizeFor2,NormalizeFor3)
    print(maximum)
    if maximum == NormalizeFor1:
        return 'a'
    elif maximum == NormalizeFor2:
        return 'b'
    else:
        return 'c'

In [367]:
predict(5)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 'b']
__ is  [0, 1]
__ is  [0, 2]
__ is  [0, 3]
__ is  [0, 4]
__ is  [0, 5]
NormalizeFor1 for  0
__ is  [0, 1]
__ is  [0, 2]
__ is  [0, 3]
__ is  [0, 4]
__ is  [0, 5]
NormalizeFor2 for  0
__ is  [0, 1]
__ is  [0, 2]
__ is  [0, 3]
__ is  [0, 4]
__ is  [0, 5]
NormalizeFor3 for  0
0


'a'

In [ ]:
X_test