In [234]:
import pandas as pd
import numpy as np
import random
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

In [235]:
datavalidate = pd.DataFrame({1:[1,8,6,2,3,1,8,6,2,3],2:[1,2,1,9,5,1,8,6,2,3],3:[4,1,8,2,5,1,8,6,2,3],4:[1,2,5,6,2,1,8,6,2,3],3:[1,2,1,9,5,1,8,6,2,3],4:[1,2,1,9,5,1,8,6,2,3],5:[1,2,1,9,5,1,8,6,2,3],6:[1,2,1,9,5,1,8,6,2,3],7:[1,2,1,9,5,1,8,6,2,3],8:[1,2,1,9,5,1,8,6,2,3],10:[1,2,1,9,5,1,8,6,2,3],11:[1,2,1,9,5,1,8,6,2,3],12:[1,2,1,9,5,1,8,6,2,3],13:[1,2,1,9,5,1,8,6,2,3],14:[1,2,1,9,5,1,8,6,2,3],15:[1,2,1,9,5,1,8,6,2,3],16:[1,2,1,9,5,1,8,6,2,3],'ans' : ['a','b','a','c','b','a','b','a','c','b']})

In [236]:
# datavalidate = pd.DataFrame({1:[1,8,6,2,3,1,8,6,2,3],2:[1,2,1,9,5,1,8,6,2,3],3:[4,1,8,2,5,1,8,6,2,3],4:[1,2,5,6,2,1,8,6,2,3],3:[1,2,1,9,5,1,8,6,2,3],4:[1,2,1,9,5,1,8,6,2,3],5:[1,2,1,9,5,1,8,6,2,3],'ans' : ['a','b','a','c','b','a','b','a','c','b']})

In [237]:
datavalidate

1  2  3  4  5  6  7  8  10  11  12  13  14  15  16 ans
0  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
1  8  2  2  2  2  2  2  2   2   2   2   2   2   2   2   b
2  6  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
3  2  9  9  9  9  9  9  9   9   9   9   9   9   9   9   c
4  3  5  5  5  5  5  5  5   5   5   5   5   5   5   5   b
5  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
6  8  8  8  8  8  8  8  8   8   8   8   8   8   8   8   b
7  6  6  6  6  6  6  6  6   6   6   6   6   6   6   6   a
8  2  2  2  2  2  2  2  2   2   2   2   2   2   2   2   c
9  3  3  3  3  3  3  3  3   3   3   3   3   3   3   3   b

In [238]:
s = len(datavalidate)//2
s

5

In [239]:
cluster1 = datavalidate[0:s]
cluster2 = datavalidate[s:len(datavalidate)]

In [240]:
cluster1

1  2  3  4  5  6  7  8  10  11  12  13  14  15  16 ans
0  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
1  8  2  2  2  2  2  2  2   2   2   2   2   2   2   2   b
2  6  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
3  2  9  9  9  9  9  9  9   9   9   9   9   9   9   9   c
4  3  5  5  5  5  5  5  5   5   5   5   5   5   5   5   b

In [241]:
cluster2

1  2  3  4  5  6  7  8  10  11  12  13  14  15  16 ans
5  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
6  8  8  8  8  8  8  8  8   8   8   8   8   8   8   8   b
7  6  6  6  6  6  6  6  6   6   6   6   6   6   6   6   a
8  2  2  2  2  2  2  2  2   2   2   2   2   2   2   2   c
9  3  3  3  3  3  3  3  3   3   3   3   3   3   3   3   b

# converting the pandas dataframe into numpy arrays

In [242]:
cluster1.iloc[:,-1].values
cluster1.iloc[:, :-1].values

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]], dtype=int64)

In [243]:
cluster1.iloc[:,-1].values

array(['a', 'b', 'a', 'c', 'b'], dtype=object)

# Checking The Values

# For Cluster 1

In [244]:
X_train_cluster1, X_test_cluster1, y_train_cluster1, y_test_cluster1 = train_test_split(cluster1.iloc[:, :-1].values, cluster1.iloc[:,-1].values, test_size=0.4)

In [245]:
X_train_cluster1

array([[8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [246]:
y_train_cluster1

array(['b', 'b', 'a'], dtype=object)

In [247]:
X_test_cluster1

array([[2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [248]:
 y_test_cluster1

array(['c', 'a'], dtype=object)

In [249]:
X_train_cluster2, X_test_cluster2, y_train_cluster2, y_test_cluster2 = train_test_split(cluster2.iloc[:, :-1].values, cluster2.iloc[:,-1].values, test_size=0.4)

# For Cluster 2

In [250]:
X_train_cluster2

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int64)

In [251]:
y_train_cluster2

array(['b', 'a', 'c'], dtype=object)

In [252]:
X_test_cluster2

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [253]:
y_test_cluster2

array(['b', 'a'], dtype=object)

In [254]:
No_of_test_cases_cluster1,No_of_test_cases_cluster2 = X_test_cluster1.shape[0],X_test_cluster2.shape[0]
print(No_of_test_cases_cluster1,"   ",No_of_test_cases_cluster2)

2     2


In [255]:
No_of_train_cluster1,No_of_train_cluster2 = X_train_cluster1.shape[0],X_train_cluster2.shape[0]
print(No_of_train_cluster1,"   ",No_of_train_cluster2)

3     3


In [256]:
No_of_columms_cluster1,No_of_columms_cluster2  = len(cluster1.columns),len(cluster2.columns)
print(No_of_columms_cluster1,"    ",No_of_columms_cluster2)

16      16


In [257]:
import math
def euclideanDistance(instance1, instance2, length):
	distance = 0
	distance = (instance1 - instance2)
	return abs(distance)

In [258]:
distances = []
import operator

In [259]:
clus1 = {"x_train":X_train_cluster1,"y_train":y_train_cluster1,
         "x_test":X_test_cluster1,"y_test":y_test_cluster1,"No_of_test_cases":No_of_test_cases_cluster1,
         "No_of_columms":No_of_columms_cluster1,"No_of_train":No_of_train_cluster1
        }
clus2 = {"x_train":X_train_cluster2,"y_train":y_train_cluster2,
         "x_test":X_test_cluster2,"y_test":y_test_cluster2,"No_of_test_cases":No_of_test_cases_cluster2,
         "No_of_columms":No_of_columms_cluster1,"No_of_train":No_of_train_cluster1
        }
cluster = {0:clus1,1:clus2}


In [260]:
cluster[0]

{'x_train': array([[8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64),
 'y_train': array(['b', 'b', 'a'], dtype=object),
 'x_test': array([[2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64),
 'y_test': array(['c', 'a'], dtype=object),
 'No_of_test_cases': 2,
 'No_of_columms': 16,
 'No_of_train': 3}

In [261]:
cluster[1]

{'x_train': array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int64),
 'y_train': array(['b', 'a', 'c'], dtype=object),
 'x_test': array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64),
 'y_test': array(['b', 'a'], dtype=object),
 'No_of_test_cases': 2,
 'No_of_columms': 16,
 'No_of_train': 3}

In [262]:
# k = 3
# NeighboursSetDict1 = []
# # NeighboursSetDict2 = []

# for y in range(No_of_test_cases_cluster1):
#     NeighboursSet = []
#     for x in range(No_of_columms_cluster1-1):
        
#         print("x is",x)
#         distances = []
#         for i in range(No_of_train_cluster1):
#             print("x train is ",X_train_cluster1[i][x])
#             dist = euclideanDistance(X_train_cluster1[i][x],X_test_cluster1[y][x],1)
#             distances.append((X_train_cluster1[i][x], dist))
#             print("each distance ",distances)
#         distances.sort(key=operator.itemgetter(1))
#         print(distances ," heer")
#         neighbors = []
#         for x in range(k):
#             neighbors.append(distances[x][0])
#             print(neighbors)
#         NeighboursSet.append(neighbors)
        
#     NeighboursSetDict1.append(NeighboursSet)
# NeighboursSetDict1

In [263]:
cluster[1]["x_test"].shape[0]

2

In [264]:
k = 2
NeighboursSetDict1 = []
NeighboursSetDict2 = []
NeighboursSetDict = {0:NeighboursSetDict1,1:NeighboursSetDict2}
for _ in range(2):
    for y in range(cluster[_]["No_of_test_cases"]):
        print("Test Cases will be --->",cluster[_]["x_test"][y])
        NeighboursSet = []
        for x in range(cluster[_]["No_of_columms"]-1):

#             print("x is",x)
            distances = []
            for i in range(cluster[_]["No_of_train"]):
#                 print("x train is ",cluster[_]["x_train"][i][x])
                dist = euclideanDistance(cluster[_]["x_train"][i][x],cluster[_]["x_test"][y][x],1)
                distances.append((cluster[_]["x_train"][i][x], dist))
                print("  each distance for test data {0} and train data {1} is {2}".format(cluster[_]["x_test"][y][x],cluster[_]["x_train"][i][x],distances))
            distances.sort(key=operator.itemgetter(1))
            print("          sorted",distances)
            neighbors = []
            for x in range(k):
                neighbors.append(distances[x][0])
            print("      neighbours are",neighbors)
            NeighboursSet.append(neighbors)
        print("      NeighboursSet for Each test case",NeighboursSet)
        NeighboursSetDict[_].append(NeighboursSet)
    NeighboursSetDict[_]

Test Cases will be ---> [2 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
  each distance for test data 2 and train data 8 is [(8, 6)]
  each distance for test data 2 and train data 3 is [(8, 6), (3, 1)]
  each distance for test data 2 and train data 6 is [(8, 6), (3, 1), (6, 4)]
          sorted [(3, 1), (6, 4), (8, 6)]
      neighbours are [3, 6]
  each distance for test data 9 and train data 2 is [(2, 7)]
  each distance for test data 9 and train data 5 is [(2, 7), (5, 4)]
  each distance for test data 9 and train data 1 is [(2, 7), (5, 4), (1, 8)]
          sorted [(5, 4), (2, 7), (1, 8)]
      neighbours are [5, 2]
  each distance for test data 9 and train data 2 is [(2, 7)]
  each distance for test data 9 and train data 5 is [(2, 7), (5, 4)]
  each distance for test data 9 and train data 1 is [(2, 7), (5, 4), (1, 8)]
          sorted [(5, 4), (2, 7), (1, 8)]
      neighbours are [5, 2]
  each distance for test data 9 and train data 2 is [(2, 7)]
  each distance for test data 9 and train data 5 is 

# Here, k = 2,so every sublist in the list has two elements 

The values we will find by using function common will give the feature value of any row in the x_train,not the index to the row which knn find outs to be nearest .
So ,if we found out the corresponding dependent variable of the row in which this feature value lies,we will get the result .

In [265]:
NeighboursSetDict[0]

[[[3, 6],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2],
  [5, 2]],
 [[3, 6],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2],
  [1, 2]]]

In [266]:
NeighboursSetDict[0][0]    #first index refer to cluster and then next index to test case

[[3, 6],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2],
 [5, 2]]

In [267]:
NeighboursSetDict[1]

[[[2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6]],
 [[2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6],
  [2, 6]]]

In [268]:
# Function to find common elements in n arrays 
def commonElements(NeighboursSet): 
      
    # initialize result with first array as a set 
    result = set(NeighboursSet[0]) 
  
    # now iterate through list of arrays starting from 
    # second array and take intersection_update() of  
    # each array with result. Every operation will  
    # update value of result with common values in 
    # result set and intersected set 
    for currSet in NeighboursSet[1:]: 
        result.intersection_update(currSet) 
  
    return list(result)

In [278]:
common_for_cluster1_for_1st_test = commonElements(NeighboursSetDict[0][0])
common_for_cluster1_for_1st_test

[]

In [277]:
common

[2]

In [273]:
common_for_cluster1_for_2nd_test = commonElements(NeighboursSetDict[0][1])
common_for_cluster1_for_2nd_test

[]

In [279]:
final_common  = set(common_for_cluster1_for_1st_test) - (set(common_for_cluster1_for_1st_test) - set(common_for_cluster1_for_2nd_test))

In [280]:
final_common

set()

In [281]:
common_for_cluster2_for_1st_test = commonElements(NeighboursSetDict[1][0])
common_for_cluster2_for_1st_test

[2, 6]

In [282]:
common_for_cluster2_for_2nd_test = commonElements(NeighboursSetDict[1][1])
common_for_cluster2_for_2nd_test

[2, 6]

In [283]:
final_common  = set(common_for_cluster2_for_1st_test) - (set(common_for_cluster2_for_1st_test) - set(common_for_cluster2_for_2nd_test))

In [284]:
final_common

{2, 6}