In [20]:
import pandas as pd
import numpy as np
import random
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

In [21]:
dataframe_new = pd.DataFrame({1:[1,8,6,2,3,1,8,6,2,3],2:[1,2,1,9,5,1,8,6,2,3],3:[4,1,8,2,5,1,8,6,2,3],4:[1,2,5,6,2,1,8,6,2,3],3:[1,2,1,9,5,1,8,6,2,3],4:[1,2,1,9,5,1,8,6,2,3],5:[1,2,1,9,5,1,8,6,2,3],6:[1,2,1,9,5,1,8,6,2,3],7:[1,2,1,9,5,1,8,6,2,3],8:[1,2,1,9,5,1,8,6,2,3],10:[1,2,1,9,5,1,8,6,2,3],11:[1,2,1,9,5,1,8,6,2,3],12:[1,2,1,9,5,1,8,6,2,3],13:[1,2,1,9,5,1,8,6,2,3],14:[1,2,1,9,5,1,8,6,2,3],15:[1,2,1,9,5,1,8,6,2,3],16:[1,2,1,9,5,1,8,6,2,3],'ans' : ['a','b','a','c','b','a','b','a','c','b']})

In [22]:
dataframe_new

1  2  3  4  5  6  7  8  10  11  12  13  14  15  16 ans
0  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
1  8  2  2  2  2  2  2  2   2   2   2   2   2   2   2   b
2  6  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
3  2  9  9  9  9  9  9  9   9   9   9   9   9   9   9   c
4  3  5  5  5  5  5  5  5   5   5   5   5   5   5   5   b
5  1  1  1  1  1  1  1  1   1   1   1   1   1   1   1   a
6  8  8  8  8  8  8  8  8   8   8   8   8   8   8   8   b
7  6  6  6  6  6  6  6  6   6   6   6   6   6   6   6   a
8  2  2  2  2  2  2  2  2   2   2   2   2   2   2   2   c
9  3  3  3  3  3  3  3  3   3   3   3   3   3   3   3   b

In [23]:
row,col = dataframe_new.shape
row
col

16

In [24]:
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(dataframe_new.iloc[:, :-1].values, dataframe_new.iloc[:,1].values, test_size=0.4)


In [25]:
X_train_new,

(array([[3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]], dtype=int64),)

In [37]:
X_train_new[0:4]

array([[3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [38]:
X_train_new.shape


(6, 15)

In [47]:
def Create_cluster(trainingSet):
    Rows = trainingSet.shape[0]
    cluster = 2
#     here we are using cluster equal to 2 
    x,y =trainingSet[0:(int(Rows/2))],trainingSet[int((Rows/2)):Rows]
    return x,y

In [48]:
Cluster_1_train,Cluster_2_train = Create_cluster(X_train_new)

In [49]:
Cluster_1_train,Cluster_2_train

(array([[3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int64),
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]], dtype=int64))

In [51]:
X_test_new

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int64)

In [52]:
No_of_test_cases = X_test_new.shape[0]
print(No_of_test_cases)
No_of_train = X_train_new.shape[0]
print(No_of_train)
No_of_columms = len(dataframe_new.columns)
print(No_of_columms)

4
6
16


In [53]:

import math
def euclideanDistance(instance1, instance2, length):
	distance = 0
	distance = (instance1 - instance2)
	return abs(distance)

In [54]:
distances = []
import operator

In [266]:
k = 3
NeighboursSetDict = []

for y in range(No_of_test_cases):
    NeighboursSet = []
    for x in range(No_of_columms-1):
        
        print("x is",x)
        distances = []
        for i in range(No_of_train):
            print("x train is ",X_train_new[i][x])
            dist = euclideanDistance(X_train_new[i][x],X_test_new[y][x],1)
            distances.append((X_train_new[i][x], dist))
            print("each distance ",distances)
        distances.sort(key=operator.itemgetter(1))
        print(distances ," heer")
        neighbors = []
        for x in range(k):
            neighbors.append(distances[x][0])
            print(neighbors)
        NeighboursSet.append(neighbors)
        
    NeighboursSetDict.append(NeighboursSet)
NeighboursSetDict

x is 0
x train is  6
each distance  [(6, 2)]
x train is  6
each distance  [(6, 2), (6, 2)]
x train is  1
each distance  [(6, 2), (6, 2), (1, 7)]
x train is  3
each distance  [(6, 2), (6, 2), (1, 7), (3, 5)]
x train is  1
each distance  [(6, 2), (6, 2), (1, 7), (3, 5), (1, 7)]
x train is  8
each distance  [(6, 2), (6, 2), (1, 7), (3, 5), (1, 7), (8, 0)]
[(8, 0), (6, 2), (6, 2), (3, 5), (1, 7), (1, 7)]  heer
[8]
[8, 6]
[8, 6, 6]
x is 1
x train is  1
each distance  [(1, 7)]
x train is  6
each distance  [(1, 7), (6, 2)]
x train is  1
each distance  [(1, 7), (6, 2), (1, 7)]
x train is  3
each distance  [(1, 7), (6, 2), (1, 7), (3, 5)]
x train is  1
each distance  [(1, 7), (6, 2), (1, 7), (3, 5), (1, 7)]
x train is  2
each distance  [(1, 7), (6, 2), (1, 7), (3, 5), (1, 7), (2, 6)]
[(6, 2), (3, 5), (2, 6), (1, 7), (1, 7), (1, 7)]  heer
[6]
[6, 3]
[6, 3, 2]
x is 2
x train is  1
each distance  [(1, 7)]
x train is  6
each distance  [(1, 7), (6, 2)]
x train is  1
each distance  [(1, 7), (6, 2), (

[6, 3, 2]
x is 8
x train is  1
each distance  [(1, 4)]
x train is  6
each distance  [(1, 4), (6, 1)]
x train is  1
each distance  [(1, 4), (6, 1), (1, 4)]
x train is  3
each distance  [(1, 4), (6, 1), (1, 4), (3, 2)]
x train is  1
each distance  [(1, 4), (6, 1), (1, 4), (3, 2), (1, 4)]
x train is  2
each distance  [(1, 4), (6, 1), (1, 4), (3, 2), (1, 4), (2, 3)]
[(6, 1), (3, 2), (2, 3), (1, 4), (1, 4), (1, 4)]  heer
[6]
[6, 3]
[6, 3, 2]
x is 9
x train is  1
each distance  [(1, 4)]
x train is  6
each distance  [(1, 4), (6, 1)]
x train is  1
each distance  [(1, 4), (6, 1), (1, 4)]
x train is  3
each distance  [(1, 4), (6, 1), (1, 4), (3, 2)]
x train is  1
each distance  [(1, 4), (6, 1), (1, 4), (3, 2), (1, 4)]
x train is  2
each distance  [(1, 4), (6, 1), (1, 4), (3, 2), (1, 4), (2, 3)]
[(6, 1), (3, 2), (2, 3), (1, 4), (1, 4), (1, 4)]  heer
[6]
[6, 3]
[6, 3, 2]
x is 10
x train is  1
each distance  [(1, 4)]
x train is  6
each distance  [(1, 4), (6, 1)]
x train is  1
each distance  [(1, 4)

[[[8, 6, 6],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2]],
 [[1, 3, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1]],
 [[1, 3, 1],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2]],
 [[3, 1, 1],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2]]]

In [267]:
NeighboursSetDict[0]

[[8, 6, 6],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2],
 [6, 3, 2]]

In [268]:
NeighboursSetDict[1]

[[1, 3, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1],
 [2, 1, 1]]

In [269]:
# Function to find common elements in n arrays 
def commonElements(NeighboursSet): 
      
    # initialize result with first array as a set 
    result = set(NeighboursSet[0]) 
  
    # now iterate through list of arrays starting from 
    # second array and take intersection_update() of  
    # each array with result. Every operation will  
    # update value of result with common values in 
    # result set and intersected set 
    for currSet in NeighboursSet[1:]: 
        result.intersection_update(currSet) 
  
    return list(result) 

In [270]:
common = commonElements(NeighboursSetDict[0])

In [271]:
common

[6]

In [272]:
common = commonElements(NeighboursSetDict[1])
common

[1]

In [273]:
NeighboursSetDict[]

[[[8, 6, 6],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2]],
 [[1, 3, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1],
  [2, 1, 1]],
 [[1, 3, 1],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2]],
 [[3, 1, 1],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2],
  [6, 3, 2]]]

In [274]:
for _ in NeighboursSetDict:
    common = commonElements(NeighboursSetDict[0])
    print(common)

[6]
[6]
[6]
[6]
