In [1]:
import pandas as pd
import numpy as np
import random
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

In [2]:
classifier_list = []
data1 = random.sample(range(1, 100), 20)
data2 = random.sample(range(1, 100), 20)
data3 = random.sample(range(1, 100), 20)
data4 = random.sample(range(1, 100), 20)
data5 = random.sample(range(1, 100), 20)
for x in range(20):
    classifier = (random.sample(range(97, 100), 1))
    classifier = chr(classifier[0])
#     print(classifier)
    classifier_list.append(classifier)


In [28]:
dataframe = pd.DataFrame({1:data1,2:data2,3:data3,4:data4,5:data5,'class':classifier_list})
dataframe_new = pd.DataFrame({1:[5,8,6,1,3],2:[1,2,7,9,5],3:[4,7,8,9,5],'ans' : ['a','b','a','c','b']})

In [4]:
row,col = dataframe.shape
row

20

In [29]:
row,col = dataframe_new.shape
row

5

In [5]:
# # 
# trainingSet = []
# testSet = []
# # x_test = []
# # y_test = []

In [6]:
# import random
# def loadDataset(dataframe, split, trainingSet=[] , testSet=[]):
# # 	with open(filename, 'rb') as csvfile:
# # 	    lines = csv.reader(csvfile)
# # 	    dataset = list(lines)
# 	    for x in range(20):
# 	        for y in range(5):
# # 	            dataframe[x][y] = float(dataframe[x][y])
# 	        if random.random() < split:
# 	            trainingSet.append(dataframe[x])
# 	        else:
# 	            testSet.append(dataframe[x])

In [7]:
# loadDataset(dataframe,0.66,trainingSet,testSet)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(dataframe.iloc[:, :-1].values, dataframe.iloc[:,1].values, test_size=0.2)
# print (X_train.shape, y_train.shape)
# print (X_test.shape, y_test.shape)

In [31]:
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(dataframe_new.iloc[:, :-1].values, dataframe_new.iloc[:,1].values, test_size=0.2)


In [9]:
X_train.shape,y_train

((16, 5),
 array([58,  5, 20, 26, 48, 27, 59, 83, 51, 17, 70, 63, 74, 30, 97, 41], dtype=int64))

In [32]:
X_train_new.shape,y_train_new

((4, 3), array([5, 1, 7, 9], dtype=int64))

In [10]:

import math
def euclideanDistance(instance1, instance2, length):
	distance = 0
	distance = (instance1 - instance2)
	return abs(distance)

In [11]:
X_train[2][0]


20

In [12]:
y_train.shape,X_train.shape

((16,), (16, 5))

In [13]:
euclideanDistance(X_train[0][0],X_test[0][0],1)

31

In [14]:
distances = []
import operator

In [15]:
for i in range(16):
#     print(X_train[i][0])
    dist = euclideanDistance(X_train[i][0],X_test[0][0],1)
    distances.append((X_train[i], dist))

In [16]:
distances.sort(key=operator.itemgetter(1))

In [17]:
distances

[(array([48, 26, 10, 70, 31], dtype=int64), 1),
 (array([46, 17, 49, 41, 75], dtype=int64), 1),
 (array([42, 74, 54, 19, 90], dtype=int64), 5),
 (array([29, 27, 90, 95, 86], dtype=int64), 18),
 (array([66, 70,  2, 22, 20], dtype=int64), 19),
 (array([25, 41, 71, 94, 84], dtype=int64), 22),
 (array([71, 51, 29, 46, 92], dtype=int64), 24),
 (array([20, 20, 34, 28, 35], dtype=int64), 27),
 (array([76, 59, 98, 74, 26], dtype=int64), 29),
 (array([77, 48, 69, 52, 21], dtype=int64), 30),
 (array([78, 58, 19, 62, 93], dtype=int64), 31),
 (array([12, 83, 67, 34, 54], dtype=int64), 35),
 (array([84,  5, 32, 71, 32], dtype=int64), 37),
 (array([87, 97, 60, 90, 70], dtype=int64), 40),
 (array([ 3, 63, 97, 48, 36], dtype=int64), 44),
 (array([ 2, 30, 24, 37,  2], dtype=int64), 45)]

In [18]:
distances[0:5]

[(array([48, 26, 10, 70, 31], dtype=int64), 1),
 (array([46, 17, 49, 41, 75], dtype=int64), 1),
 (array([42, 74, 54, 19, 90], dtype=int64), 5),
 (array([29, 27, 90, 95, 86], dtype=int64), 18),
 (array([66, 70,  2, 22, 20], dtype=int64), 19)]

In [19]:
neighbors = []
for x in range(5):
    neighbors.append(distances[x][0])
neighbors

[array([48, 26, 10, 70, 31], dtype=int64),
 array([46, 17, 49, 41, 75], dtype=int64),
 array([42, 74, 54, 19, 90], dtype=int64),
 array([29, 27, 90, 95, 86], dtype=int64),
 array([66, 70,  2, 22, 20], dtype=int64)]

In [20]:
neighbors_list = {}
neighbors_list[X_test[0][0]] = neighbors

In [21]:
neighbors_list

{47: [array([48, 26, 10, 70, 31], dtype=int64),
  array([46, 17, 49, 41, 75], dtype=int64),
  array([42, 74, 54, 19, 90], dtype=int64),
  array([29, 27, 90, 95, 86], dtype=int64),
  array([66, 70,  2, 22, 20], dtype=int64)]}

In [186]:
for y in neighbors_list:
    for z in y:
        print(z)

IndexError: invalid index to scalar variable.

In [190]:
[x[1] for x in neighbors_list]

IndexError: invalid index to scalar variable.

In [23]:
X_test

array([[47, 39, 58, 86, 82],
       [36, 32, 44,  8, 33],
       [73, 71, 18, 53, 94],
       [49, 11, 73, 25, 40]], dtype=int64)

In [36]:
X_test_new


array([[8, 2, 7]], dtype=int64)

In [24]:
# import pdb

for y in range(3):
    for i in range(16):
    #     print(X_train[i][0])
#         pdb.set_trace()
        dist = euclideanDistance(X_train[i][0],X_test[y][0],1)
        distances.append((X_train[i], dist))

In [25]:
distances

[(array([48, 26, 10, 70, 31], dtype=int64), 1),
 (array([46, 17, 49, 41, 75], dtype=int64), 1),
 (array([42, 74, 54, 19, 90], dtype=int64), 5),
 (array([29, 27, 90, 95, 86], dtype=int64), 18),
 (array([66, 70,  2, 22, 20], dtype=int64), 19),
 (array([25, 41, 71, 94, 84], dtype=int64), 22),
 (array([71, 51, 29, 46, 92], dtype=int64), 24),
 (array([20, 20, 34, 28, 35], dtype=int64), 27),
 (array([76, 59, 98, 74, 26], dtype=int64), 29),
 (array([77, 48, 69, 52, 21], dtype=int64), 30),
 (array([78, 58, 19, 62, 93], dtype=int64), 31),
 (array([12, 83, 67, 34, 54], dtype=int64), 35),
 (array([84,  5, 32, 71, 32], dtype=int64), 37),
 (array([87, 97, 60, 90, 70], dtype=int64), 40),
 (array([ 3, 63, 97, 48, 36], dtype=int64), 44),
 (array([ 2, 30, 24, 37,  2], dtype=int64), 45),
 (array([78, 58, 19, 62, 93], dtype=int64), 31),
 (array([84,  5, 32, 71, 32], dtype=int64), 37),
 (array([20, 20, 34, 28, 35], dtype=int64), 27),
 (array([48, 26, 10, 70, 31], dtype=int64), 1),
 (array([77, 48, 69, 52,

In [38]:
distances1 = []
for y in range(1):
    for i in range(4):
    #     print(X_train[i][0])
#         pdb.set_trace()
        for x in range(3):
            dist = euclideanDistance(X_train_new[i][x],X_test_new[y][x],1)
            distances.append((X_train_new[i][x], dist))

In [39]:
distances1

[(3, 5),
 (5, 3),
 (5, 2),
 (5, 3),
 (1, 1),
 (4, 3),
 (6, 2),
 (7, 5),
 (8, 1),
 (1, 7),
 (9, 7),
 (9, 2)]

In [37]:
dataframe_new

1  2  3 ans
0  5  1  4   a
1  8  2  7   b
2  6  7  8   a
3  1  9  9   c
4  3  5  5   b